# Generated by Django 5.0.3 on 2024-03-16 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(default='Jose Diaz', max_length=50, verbose_name='Nombres Completos'),
            preserve_default=False,
        ),
    ]
